// Static deals data for GitHub Pages deployment
// Empty for now - only Amazon products you specifically provide will be added
export const staticDeals = [
  {
    id: 1,
    name: "Premium Amazon Product 1",
    description: "Amazing product with great features",
    price: "$99.99",
    oldPrice: "$149.99",
    image: "https://via.placeholder.com/300x300/5d3a9b/white?text=Product+1",
    link: "https://amzn.to/4nGXCMx",
    store: "Amazon",
    category: "Electronics",
    discountPercent: "33",
    rating: "4.5",
    reviews: "1,234",
    isSponsored: true,
    tags: ["amazon", "electronics"]
  },
  {
    id: 2,
    name: "Premium Amazon Product 2",
    description: "High-quality product at an amazing price",
    price: "$79.99",
    oldPrice: "$119.99",
    image: "https://via.placeholder.com/300x300/7b4bb8/white?text=Product+2",
    link: "https://amzn.to/4oyZ5pl",
    store: "Amazon",
    category: "Home & Garden",
    discountPercent: "33",
    rating: "4.7",
    reviews: "856",
    isSponsored: true,
    tags: ["amazon", "home"]
  },
  {
    id: 3,
    name: "Premium Amazon Product 3",
    description: "Top-rated product with excellent reviews",
    price: "$129.99",
    oldPrice: "$179.99",
    image: "https://via.placeholder.com/300x300/8b5cc8/white?text=Product+3",
    link: "https://amzn.to/3LKREg4",
    store: "Amazon",
    category: "Beauty",
    discountPercent: "28",
    rating: "4.8",
    reviews: "2,145",
    isSponsored: true,
    tags: ["amazon", "beauty"]
  },
  {
    id: 4,
    name: "Premium Amazon Product 4",
    description: "Must-have item with incredible value",
    price: "$59.99",
    oldPrice: "$89.99",
    image: "https://via.placeholder.com/300x300/9b6dd8/white?text=Product+4",
    link: "https://amzn.to/4oqQC7G",
    store: "Amazon",
    category: "Sports",
    discountPercent: "33",
    rating: "4.6",
    reviews: "743",
    isSponsored: true,
    tags: ["amazon", "sports"]
  },
  {
    id: 5,
    name: "Premium Amazon Product 5",
    description: "Best-selling product with amazing features",
    price: "$149.99",
    oldPrice: "$199.99",
    image: "https://via.placeholder.com/300x300/ab7ee8/white?text=Product+5",
    link: "https://amzn.to/4qGAJeM",
    store: "Amazon",
    category: "Clothing",
    discountPercent: "25",
    rating: "4.9",
    reviews: "3,267",
    isSponsored: true,
    tags: ["amazon", "clothing"]
  },
  {
    id: 6,
    name: "Premium Amazon Product 6",
    description: "Innovative product with cutting-edge technology",
    price: "$89.99",
    oldPrice: "$129.99",
    image: "https://via.placeholder.com/300x300/bb8ff8/white?text=Product+6",
    link: "https://amzn.to/3WBmOcf",
    store: "Amazon",
    category: "Electronics",
    discountPercent: "31",
    rating: "4.4",
    reviews: "1,892",
    isSponsored: true,
    tags: ["amazon", "electronics"]
  },
  {
    id: 7,
    name: "Premium Amazon Product 7",
    description: "Perfect solution for everyday needs",
    price: "$39.99",
    oldPrice: "$59.99",
    image: "https://via.placeholder.com/300x300/cba0ff/white?text=Product+7",
    link: "https://amzn.to/47VXKTv",
    store: "Amazon",
    category: "Home & Garden",
    discountPercent: "33",
    rating: "4.3",
    reviews: "567",
    isSponsored: true,
    tags: ["amazon", "home"]
  },
  {
    id: 8,
    name: "Premium Amazon Product 8",
    description: "High-performance product with great durability",
    price: "$199.99",
    oldPrice: "$299.99",
    image: "https://via.placeholder.com/300x300/dbb1ff/white?text=Product+8",
    link: "https://amzn.to/3JJzwCQ",
    store: "Amazon",
    category: "Automotive",
    discountPercent: "33",
    rating: "4.7",
    reviews: "1,456",
    isSponsored: true,
    tags: ["amazon", "automotive"]
  },
  {
    id: 9,
    name: "Premium Amazon Product 9",
    description: "Essential item with unbeatable price",
    price: "$69.99",
    oldPrice: "$99.99",
    image: "https://via.placeholder.com/300x300/ebc2ff/white?text=Product+9",
    link: "https://amzn.to/4ou29mE",
    store: "Amazon",
    category: "Books",
    discountPercent: "30",
    rating: "4.5",
    reviews: "892",
    isSponsored: true,
    tags: ["amazon", "books"]
  },
  {
    id: 10,
    name: "Amazing Tech Gadget",
    description: "Latest technology at incredible price",
    price: "$159.99",
    oldPrice: "$229.99",
    image: "https://via.placeholder.com/300x300/5d3a9b/white?text=Tech+10",
    link: "https://amzn.to/4nGXCMx",
    store: "Amazon",
    category: "Electronics",
    discountPercent: "30",
    rating: "4.6",
    reviews: "1,567",
    isSponsored: true,
    tags: ["amazon", "electronics"]
  },
  {
    id: 11,
    name: "Stylish Fashion Item",
    description: "Trendy fashion at great value",
    price: "$45.99",
    oldPrice: "$69.99",
    image: "https://via.placeholder.com/300x300/7b4bb8/white?text=Fashion+11",
    link: "https://amzn.to/4oyZ5pl",
    store: "Amazon",
    category: "Clothing",
    discountPercent: "34",
    rating: "4.4",
    reviews: "892",
    isSponsored: true,
    tags: ["amazon", "clothing"]
  },
  {
    id: 12,
    name: "Home Essentials Kit",
    description: "Everything you need for home",
    price: "$89.99",
    oldPrice: "$129.99",
    image: "https://via.placeholder.com/300x300/8b5cc8/white?text=Home+12",
    link: "https://amzn.to/3LKREg4",
    store: "Amazon",
    category: "Home & Garden",
    discountPercent: "31",
    rating: "4.7",
    reviews: "2,134",
    isSponsored: true,
    tags: ["amazon", "home"]
  },
  {
    id: 13,
    name: "Fitness Equipment Pro",
    description: "Professional grade fitness gear",
    price: "$199.99",
    oldPrice: "$299.99",
    image: "https://via.placeholder.com/300x300/9b6dd8/white?text=Fitness+13",
    link: "https://amzn.to/4oqQC7G",
    store: "Amazon",
    category: "Sports",
    discountPercent: "33",
    rating: "4.8",
    reviews: "3,245",
    isSponsored: true,
    tags: ["amazon", "sports"]
  },
  {
    id: 14,
    name: "Beauty Essentials Set",
    description: "Complete beauty collection",
    price: "$79.99",
    oldPrice: "$119.99",
    image: "https://via.placeholder.com/300x300/ab7ee8/white?text=Beauty+14",
    link: "https://amzn.to/4qGAJeM",
    store: "Amazon",
    category: "Beauty",
    discountPercent: "33",
    rating: "4.5",
    reviews: "1,876",
    isSponsored: true,
    tags: ["amazon", "beauty"]
  },
  {
    id: 15,
    name: "Smart Kitchen Appliance",
    description: "Modern kitchen convenience",
    price: "$129.99",
    oldPrice: "$189.99",
    image: "https://via.placeholder.com/300x300/bb8ff8/white?text=Kitchen+15",
    link: "https://amzn.to/3WBmOcf",
    store: "Amazon",
    category: "Home & Garden",
    discountPercent: "32",
    rating: "4.6",
    reviews: "1,432",
    isSponsored: true,
    tags: ["amazon", "home"]
  },
  {
    id: 16,
    name: "Premium Audio Device",
    description: "Crystal clear sound quality",
    price: "$249.99",
    oldPrice: "$349.99",
    image: "https://via.placeholder.com/300x300/cba0ff/white?text=Audio+16",
    link: "https://amzn.to/47VXKTv",
    store: "Amazon",
    category: "Electronics",
    discountPercent: "29",
    rating: "4.9",
    reviews: "4,567",
    isSponsored: true,
    tags: ["amazon", "electronics"]
  },
  {
    id: 17,
    name: "Outdoor Adventure Gear",
    description: "Perfect for outdoor enthusiasts",
    price: "$99.99",
    oldPrice: "$149.99",
    image: "https://via.placeholder.com/300x300/dbb1ff/white?text=Outdoor+17",
    link: "https://amzn.to/3JJzwCQ",
    store: "Amazon",
    category: "Sports",
    discountPercent: "33",
    rating: "4.4",
    reviews: "987",
    isSponsored: true,
    tags: ["amazon", "sports"]
  },
  {
    id: 18,
    name: "Educational Books Bundle",
    description: "Knowledge at your fingertips",
    price: "$39.99",
    oldPrice: "$59.99",
    image: "https://via.placeholder.com/300x300/ebc2ff/white?text=Books+18",
    link: "https://amzn.to/4ou29mE",
    store: "Amazon",
    category: "Books",
    discountPercent: "33",
    rating: "4.7",
    reviews: "2,345",
    isSponsored: true,
    tags: ["amazon", "books"]
  },
  {
    id: 19,
    name: "Professional Tools Set",
    description: "High-quality tools for professionals",
    price: "$179.99",
    oldPrice: "$249.99",
    image: "https://via.placeholder.com/300x300/5d3a9b/white?text=Tools+19",
    link: "https://amzn.to/4nGXCMx",
    store: "Amazon",
    category: "Automotive",
    discountPercent: "28",
    rating: "4.6",
    reviews: "1,234",
    isSponsored: true,
    tags: ["amazon", "automotive"]
  },
  {
    id: 20,
    name: "Luxury Skincare Bundle",
    description: "Premium skincare routine",
    price: "$119.99",
    oldPrice: "$179.99",
    image: "https://via.placeholder.com/300x300/7b4bb8/white?text=Skincare+20",
    link: "https://amzn.to/4oyZ5pl",
    store: "Amazon",
    category: "Beauty",
    discountPercent: "33",
    rating: "4.8",
    reviews: "3,456",
    isSponsored: true,
    tags: ["amazon", "beauty"]
  },
  {
    id: 21,
    name: "Gaming Accessories Pack",
    description: "Level up your gaming experience",
    price: "$89.99",
    oldPrice: "$129.99",
    image: "https://via.placeholder.com/300x300/8b5cc8/white?text=Gaming+21",
    link: "https://amzn.to/3LKREg4",
    store: "Amazon",
    category: "Electronics",
    discountPercent: "31",
    rating: "4.5",
    reviews: "2,789",
    isSponsored: true,
    tags: ["amazon", "electronics"]
  },
  {
    id: 22,
    name: "Pet Care Essentials",
    description: "Everything your pet needs",
    price: "$59.99",
    oldPrice: "$89.99",
    image: "https://via.placeholder.com/300x300/9b6dd8/white?text=Pet+22",
    link: "https://amzn.to/4oqQC7G",
    store: "Amazon",
    category: "Pet Supplies",
    discountPercent: "33",
    rating: "4.7",
    reviews: "1,567",
    isSponsored: true,
    tags: ["amazon", "pets"]
  },
  {
    id: 23,
    name: "Office Productivity Suite",
    description: "Boost your work efficiency",
    price: "$149.99",
    oldPrice: "$219.99",
    image: "https://via.placeholder.com/300x300/ab7ee8/white?text=Office+23",
    link: "https://amzn.to/4qGAJeM",
    store: "Amazon",
    category: "Office",
    discountPercent: "32",
    rating: "4.4",
    reviews: "1,890",
    isSponsored: true,
    tags: ["amazon", "office"]
  },
  {
    id: 24,
    name: "Baby Care Collection",
    description: "Safe and gentle for babies",
    price: "$79.99",
    oldPrice: "$119.99",
    image: "https://via.placeholder.com/300x300/bb8ff8/white?text=Baby+24",
    link: "https://amzn.to/3WBmOcf",
    store: "Amazon",
    category: "Baby",
    discountPercent: "33",
    rating: "4.9",
    reviews: "4,234",
    isSponsored: true,
    tags: ["amazon", "baby"]
  },
  {
    id: 25,
    name: "Travel Accessories Kit",
    description: "Travel smart and comfortable",
    price: "$69.99",
    oldPrice: "$99.99",
    image: "https://via.placeholder.com/300x300/cba0ff/white?text=Travel+25",
    link: "https://amzn.to/47VXKTv",
    store: "Amazon",
    category: "Other",
    discountPercent: "30",
    rating: "4.6",
    reviews: "1,345",
    isSponsored: true,
    tags: ["amazon", "travel"]
  },
  {
    id: 26,
    name: "Garden Tools Pro Set",
    description: "Professional gardening equipment",
    price: "$139.99",
    oldPrice: "$199.99",
    image: "https://via.placeholder.com/300x300/dbb1ff/white?text=Garden+26",
    link: "https://amzn.to/3JJzwCQ",
    store: "Amazon",
    category: "Home & Garden",
    discountPercent: "30",
    rating: "4.5",
    reviews: "987",
    isSponsored: true,
    tags: ["amazon", "home"]
  },
  {
    id: 27,
    name: "Craft Supplies Bundle",
    description: "Unleash your creativity",
    price: "$49.99",
    oldPrice: "$74.99",
    image: "https://via.placeholder.com/300x300/ebc2ff/white?text=Craft+27",
    link: "https://amzn.to/4ou29mE",
    store: "Amazon",
    category: "Handmade",
    discountPercent: "33",
    rating: "4.7",
    reviews: "2,123",
    isSponsored: true,
    tags: ["amazon", "craft"]
  },
  {
    id: 28,
    name: "Health Monitoring Device",
    description: "Track your wellness journey",
    price: "$199.99",
    oldPrice: "$279.99",
    image: "https://via.placeholder.com/300x300/5d3a9b/white?text=Health+28",
    link: "https://amzn.to/4nGXCMx",
    store: "Amazon",
    category: "Health",
    discountPercent: "29",
    rating: "4.8",
    reviews: "3,567",
    isSponsored: true,
    tags: ["amazon", "health"]
  },
  {
    id: 29,
    name: "Educational Toys Set",
    description: "Fun learning for kids",
    price: "$89.99",
    oldPrice: "$129.99",
    image: "https://via.placeholder.com/300x300/7b4bb8/white?text=Toys+29",
    link: "https://amzn.to/4oyZ5pl",
    store: "Amazon",
    category: "Toys",
    discountPercent: "31",
    rating: "4.6",
    reviews: "1,876",
    isSponsored: true,
    tags: ["amazon", "toys"]
  },
  {
    id: 30,
    name: "Smart Security System",
    description: "Protect your home with technology",
    price: "$299.99",
    oldPrice: "$449.99",
    image: "https://via.placeholder.com/300x300/8b5cc8/white?text=Security+30",
    link: "https://amzn.to/3LKREg4",
    store: "Amazon",
    category: "Electronics",
    discountPercent: "33",
    rating: "4.9",
    reviews: "5,234",
    isSponsored: true,
    tags: ["amazon", "electronics"]
  }
];

// Categories remain the same
export const categories = [
  "all", "Electronics", "Clothing", "Home & Garden", "Beauty", 
  "Sports", "Books", "Automotive", "Health", "Toys", "Food", 
  "Office", "Baby", "Pet Supplies", "Industrial", "Handmade", "Other"
];

export const stores = ["all", "Amazon", "Walmart", "Target", "Home Depot"];

export function filterDeals(deals, category, store, searchTerm) {
  return deals.filter(deal => {
    const matchesCategory = category === "all" || deal.category === category;
    const matchesStore = store === "all" || deal.store === store;
    const matchesSearch = !searchTerm || 
      deal.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      deal.category.toLowerCase().includes(searchTerm.toLowerCase());
    
    return matchesCategory && matchesStore && matchesSearch;
  });
}

// Last updated: Ready for Amazon products